# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 093bbca41796314cb92a5ee4bd1df10b9c209fb90c8d9a754866a6a9972d14f57530edf2e43c2dc8a72ee7eaf3dc3b005fcc17c6a2b0b89821b76116d90e5f88

test:
  secret_key_base: 114f734deaa911fbdabd4a74d69c31b51bb43503107b7712c20dedfc87012e940095e927cd296a79cc7b6e070ba5eb5face3a29f374dbf8e04c7543aec0f579e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
